Repository open62541/open62541, pull requests merged in 2019-08, with the labels that each got.

#2935 Correct boolean check on input parameters
  examples/pubsub/tutorial_pubsub_subscribe.c
Labels: Component: Server, Priority: Medium, Status: Merge When Green, Type: Bug

#2957 merge: 1.0 into master
  .travis.yml
  debian/open62541-dev.install
  debian/open62541.install
  examples/pubsub/tutorial_pubsub_subscribe.c
  examples/server_ctt.c
  open62541.pc.in
  src/client/ua_client_subscriptions.c
  src/server/ua_services_nodemanagement.c
  src/ua_types.c
  tests/check_utils.c
  tests/server/check_subscription_events.c
Labels: Component: Core, Priority: High, Status: Merge When Green, Type: Maintenance

#2980 Automatically set CMake version based on git tag
  .travis.yml
  CMakeLists.txt
  appveyor.yml
  debian/update_changelog.py
  tools/cmake/SetGitBasedVersion.cmake
  tools/travis/travis_linux_script.sh
Labels: Component: CI, Priority: Medium, Status: Merge When Green, Type: Enhancement

#2994 [review] Unify license headers
  tools/nodeset_compiler/backend_open62541.py
  tools/nodeset_compiler/backend_open62541_nodes.py
  tools/nodeset_compiler/datatypes.py
  tools/nodeset_compiler/nodes.py
  tools/nodeset_compiler/nodeset.py
  tools/nodeset_compiler/nodeset_compiler.py
  tools/nodeset_compiler/nodeset_testing.py
  tools/nodeset_compiler/opaque_type_mapping.py
Labels: Component: Nodeset Compiler, Priority: Low, Status: Review Needed

#3055 fix(debian): add python dependency to dev package
  debian/control-template
Labels: Component: CI, Priority: Low, Status: Merge When Green, Type: Enhancement

#3058 fix: Improve security policy logging if invalid private key is given
  plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c
  plugins/securityPolicies/ua_securitypolicy_basic256.c
  plugins/securityPolicies/ua_securitypolicy_basic256sha256.c
Labels: Component: Encryption, Priority: Low, Status: Merge When Green, Type: Enhancement

#2960 docs: Update contributing guidelines for conventional commits
  CONTRIBUTING.md
Labels: Component: CI, Priority: Low, Status: Merge When Green, Type: Enhancement

#3061 fix(docs): Add info about pack branches
  doc/installing.rst
Labels: Component: CI, Priority: Low, Status: Merge When Green, Type: Enhancement
