Repository open62541/open62541, pull requests merged in 2019-09, with the labels that each got.

#3067 Merge 1.0 into master
  .dockerignore
  .travis.yml
  CMakeLists.txt
  Dockerfile
  README.md
  arch/network_tcp.c
  azure-pipelines.yml
  debian/control-template
  deps/base64.c
  deps/base64.h
  deps/libc_time.c
  deps/libc_time.h
  doc/installing.rst
  plugins/include/open62541/plugin/pki_default.h
  plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c
  plugins/securityPolicies/ua_securitypolicy_basic256.c
  plugins/securityPolicies/ua_securitypolicy_basic256sha256.c
  plugins/ua_config_default.c
  plugins/ua_pki_default.c
  src/client/ua_client.c
  src/pubsub/ua_pubsub.c
  src/server/ua_server.c
  src/server/ua_services_attribute.c
  src/ua_types_encoding_json.c
  src/ua_util.c
  tests/fuzz/fuzz_json_decode_encode.cc
  tests/pubsub/check_pubsub_subscribe.c
  tests/server/check_server_userspace.c
  tools/azure-devops/build.ps1
  tools/nodeset_compiler/nodes.py
  tools/nodeset_compiler/nodeset.py
  tools/nodeset_compiler/nodeset_compiler.py
  tools/travis/travis_linux_script.sh
Labels: Component: Core, Priority: Medium, Status: Merge When Green, Type: Maintenance

#3069 fix(debian): remove braces in debhelper config file
  debian/libopen62541-dev.install-template
Labels: Component: CI, Priority: Low, Status: Merge When Green, Type: Enhancement

#3071 fix(debian): syntax errors in copyright file
  debian/copyright
Labels: Component: CI, Priority: Low, Status: Merge When Green, Type: Enhancement

#3073 fix(server): Do not allow node having itself as parent. Fixes stack-overflow
  src/server/ua_services_nodemanagement.c
Labels: Component: Core, Priority: High, Status: Merge When Green, Type: Bug

#2998 docs: Add package to Arch User Repository
  doc/installing.rst
Labels: Priority: Low, Status: Review Needed
