Repository open62541/open62541, pull requests merged in 2019-07, with the labels that each got.

#2895 Set correct dependency in debian package and push version to 1.0
  CMakeLists.txt
  debian/changelog
  debian/control
  debian/copyright
  doc/installing.rst
Labels: Component: Core, Priority: Low, Status: Review Needed, Type: Enhancement

#2901 CI: Pin docutils to 0.14
  tools/travis/travis_linux_before_install.sh
Labels: Component: CI, Priority: High, Status: Pending, Type: Bug

#2902 [0.3] CI: Pin docutils to 0.14
  tools/travis/travis_linux_before_install.sh
Labels: Component: CI, Priority: High, Status: Pending, Type: Bug

#2903 [master] CI: Pin docutils to 0.14
  tools/travis/travis_linux_before_install.sh
Labels: Component: CI, Priority: High, Status: Pending, Type: Bug

#2897 DatatypeGenerator: Allow to import additional types as dependency
  tools/cmake/macros_public.cmake
  tools/generate_datatypes.py
Labels: Component: Nodeset Compiler, Priority: Medium, Status: Pending, Type: Enhancement

#2912 debian: use GNUInstallDirs vars to set multiarch-tuple in pkg-config file
  open62541.pc.in
Labels: Component: Core, Priority: Low, Status: Merge When Green, Type: Enhancement

#2910 Client: Add timeout check for publish response
  src/client/ua_client_subscriptions.c
Labels: Component: Client, Priority: Low, Status: Merge When Green, Type: Bug

#2911 Client: Add timeout check for publish response
  src/client/ua_client_subscriptions.c
Labels: Component: Client, Priority: Low, Status: Merge When Green, Type: Bug

#2872 [REVIEW] add support for websocket transport
  CMakeLists.txt
  arch/network_ws.c
  examples/tutorial_server_variable.c
  include/open62541/config.h.in
  include/open62541/network_ws.h
  plugins/include/open62541/server_config_default.h
  plugins/ua_config_default.c
  tools/cmake/Findlibwebsockets.cmake
Labels: Component: Server, Priority: Low, Status: Merge When Green, Type: Enhancement

#2908 Debian: Do not copy lib into open62541-dev to avoid overriding open62541 package
  debian/open62541-dev.install
  debian/open62541.install
Labels: Component: CI, Priority: Medium, Status: Merge When Green, Type: Bug
